server:
  port: 8085

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: controller-microservice
          uri: lb://controller-microservice
          predicates:
            - Path=/auth/**

        - id: controller-microservice
          uri: lb://controller-microservice
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - AuthenticationFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.netflix.eureka: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
