server:
  port: 9193
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Purna@123
    url: jdbc:mysql://localhost:3306/ppc-project
    username: PurnaChander
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: QueryService

  cloud:
    compatibility-verifier:
      enabled: false
#spring.cloud.compatibility-verifier.enabled=false

#flow:
#  matrix:
#    SrCreditReviewer:
#      Case: "santosh"
#      cemment: "rohit"