server:
  port: 9197
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Purna@123
    url: jdbc:mysql://localhost:3306/projecti
    username: Purnachander
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: Comment-Service
    
#eureka:
#  client:
#    healthcheck:
#      enabled: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health
