server:
  port: 8084

spring:
  application:
    name: controller-microservice
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
  datasource:
    url: jdbc:mysql://localhost:3306/projectersc
    username: PurnaChander
    password: Purna@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG
