server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: controller-microservice
          uri: lb://controller-microservice
          predicates:
            - Path=/auth/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG