server:
  port: 1999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Purna@123
    url: jdbc:mysql://localhost:3306/projecti
    username: PurnaChander
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: Message-Service

management:
  endpoints:
    web:
      exposure:
        include: "*"

