server:
  port: 9194
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Purna@123
    url: jdbc:mysql://localhost:3306/ppc-project
    username: PurnaChander
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: ActionService

  cloud:
    compatibility-verifier:
      enabled: false
#spring.cloud.compatibility-verifier.enabled=false

flow:
  matrix:
    SrCreditReviewer:
      SubmittedToHeadofPPC:
        caseStatus: Case Assigned to Head of PPC
        milestone: Head of PPC
        activityLevel: Head of PPC
        bpmStatus: Submit to Head of PPC
        profileActivityLevel: Head of PPC
        auditText: Case submitted by Sr Credit Reviewer to Head of PPC
      AssigntoCreditReviewer:
        caseStatus: Case Assigned to Credit Reviewer
        milestone: Credit Reviewer Review
        activityLevel: Credit Reviewer
        bpmStatus: Assign to Credit Reviewer
        profileActivityLevel: Credit Reviewer
        auditText: Case submitted by Sr Credit Reviewer to Credit Reviewer
      FieldworkCompleted:
        caseStatus: Case Completed by Sr Credit Reviewer
        milestone: Closed
        activityLevel: Closed
        bpmStatus: Fieldwork Completed
        profileActivityLevel: ""
        auditText: Case Closed by Sr Credit Reviewer
    HeadofPPC:
      Approve:
        caseStatus: Case Approved by Head of PPC
        milestone: Sr Credit Reviewer Review
        activityLevel: Sr Credit Reviewer
        bpmStatus: Approve
        profileActivityLevel: Sr Credit Reviewer
        auditText: Case Approved by Head of PPC and assigned to Sr credit Reviewer
      Reject:
        caseStatus: Case Rejected by Head of PPC
        milestone: Sr Credit Reviewer Review
        activityLevel: Sr Credit Reviewer
        bpmStatus: Reject
        profileActivityLevel: Sr Credit Reviewer
        auditText: Case Rejected by Head of PPC and assigned to Sr credit Reviewer
    CreditReviewer:
      SubmittoSPOC:
        activityLevel: SPOC
        auditText: Case submitted by Credit Reviewer to SPOC
      SubmittoSrCreditReviewer:
        caseStatus: Case Assigned to Sr Credit Reviewer
        milestone: Sr Credit Reviewer Review
        activityLevel: Sr Credit Reviewer
        bpmStatus: Submit to Sr Credit Reviewer
        profileActivityLevel: Sr Credit Reviewer
        auditText: Case submitted by Credit Reviewer to Sr credit Reviewer
    SPOC:
      SubmittoCreditReviewer:
        activityLevel: Credit Reviewer
        auditText: Case submitted by SPOC to Credit Reviewer



