server:
  port: 9194
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Purna@123
    url: jdbc:mysql://localhost:3306/ppc-project
    username: PurnaChander
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: ActionService

  cloud:
    compatibility-verifier:
      enabled: false
#spring.cloud.compatibility-verifier.enabled=false

flow:
  matrix:
    SrCreditReviewer:
      caseStatus: Case Assigned to Head of PPC
      milestone: Head of PPC
      activityLevel: Head of PPC
      bpmStatus: Submit to Head of PPC
      profileActivityLevel: Head of PPC
      auditText: Case submitted by Sr Credit Reviewer to Head of PPC
    AssigntoCreditReviewer:
      caseStatus: Case Assigned to Credit Reviewer
      milestone: Credit Reviewer Review
      activityLevel: Credit Reviewer
      bpmStatus: Assign to Credit Reviewer
      profileActivityLevel: Credit Reviewer
      auditText: Case submitted by Sr Credit Reviewer to Credit Reviewer