server:
  port: 9194
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Purna@123
    url: jdbc:mysql://localhost:3306/ppc-project
    username: PurnaChander
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: ActionService

  cloud:
    compatibility-verifier:
      enabled: false
#spring.cloud.compatibility-verifier.enabled=false