server:
  port: 9194  # Gateway port

spring:
  applcation:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: IDENTITY-SERVICE
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path=/api/v1/users/**

        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path=/api/v1/auth/**

        - id: Post-Service
          uri: lb://Post-Service
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - AuthenticationFilter

        - id: Comment-Service
          uri: lb://Comment-Service
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - AuthenticationFilter

        - id: Comment-Service
          uri: lb://Comment-Service
          predicates:
            - Path=/api/v1/commentsReply/**
          filters:
            - AuthenticationFilter


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka




