server:
  port: 9194  # Gateway port

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path=/api/v1/users/**

        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path=/api/v1/auth/**

        - id: Post-Service
          uri: lb://Post-Service
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - AuthenticationFilter

        - id: Comment-Service
          uri: lb://Comment-Service
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - AuthenticationFilter

        - id: Comment-Service
          uri: lb://Comment-Service
          predicates:
            - Path=/api/v1/commentsReply/**
          filters:
            - AuthenticationFilter

        - id: Like-Service
          uri: lb://Like-Service
          predicates:
            - Path=/api/v1/likes/**
          filters:
            - AuthenticationFilter

        - id: Follow-Service
          uri: lb://Follow-Service
          predicates:
            - Path=/api/follow/**
          filters:
            - AuthenticationFilter

        - id: Story-Service
          uri: lb://Story-Service
          predicates:
            - Path=/api/stories/**
          filters:
            - AuthenticationFilter

        - id: Search-Service
          uri: lb://Search-Service
          predicates:
            - Path=/api/search/**
          filters:
            - AuthenticationFilter

        - id: MessageService
          uri: lb://MessageService
          predicates:
            - Path=/api/messages/**
          filters:
            - AuthenticationFilter


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG




