server:
  port: 8083

spring:
  application:
    name: service-microservice
  datasource:
    url: jdbc:mysql://localhost:3306/projectersc
    username: PurnaChander
    password: Purna@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Enable Feign Client
feign:
  hystrix:
    enabled: true
