server:
  port: 2000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projecti
    username: PurnaChander
    password: Purna@123
  jpa:
    properties:
      hibernate:
      format-sql: true
    hibernate:
      ddl-auto: update
    show-sql: true



  application:
    name: IDENTITY-SERVICE

logging:
  level:
    org.springframework.security: DEBUG
