server:
  port: 9195
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Purna@123
    url: jdbc:mysql://localhost:3306/projecti
    username: Purnachander
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: User-Service
  mail:
    host: smtp.gmail.com
    port: 587
    username: purnachander.eidiko@gmail.com
    password: vfbd gtkv nbur gxjk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


