server:
  port: 9195

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      routes:
        - id: ActionService
          uri: lb://Action-Service
          predicates:
            - Path=/api/action/**,/api/comment/**,/api/ActionAT/**

          filters:
            - AuthenticationFilter

        - id: QueryService
          uri: lb://Query-Service
          predicates:
            - Path=/api/query/**,/api/fetch/**,/api/QueryAT/**
          filters:
            - AuthenticationFilter


      discovery:
        locator:
          enabled: true

    eureka:
      client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
          defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
